#!/usr/bin/env python3
"""
Chapter generation script for Physical AI & Humanoid Robotics textbook.

Generates MDX files following the required structure:
- Intro
- Learning Objectives (3-5 items)
- Hook
- Concept
- Mermaid Diagram
- Code Example
- Exercises
- Summary
- Preview Next Chapter
"""

import os
import sys
from pathlib import Path
from datetime import datetime
from typing import Dict, List, Optional
import yaml


def create_chapter_template(
    title: str,
    description: str,
    learning_outcomes: List[str],
    prerequisites: List[str],
    part_name: str,
    chapter_num: int,
    chapter_slug: str
) -> str:
    """
    Creates a chapter template with the required structure.

    Args:
        title: Chapter title
        description: Chapter description
        learning_outcomes: List of learning outcomes (3-5 items)
        prerequisites: List of prerequisites
        part_name: Name of the part (e.g., "part-1-foundations-lab")
        chapter_num: Chapter number
        chapter_slug: Chapter slug for filename

    Returns:
        String containing the MDX content
    """
    template = f"""---
title: "{title}"
description: "{description}"
learning_outcomes:
{chr(10).join([f'  - "{outcome}"' for outcome in learning_outcomes])}
prerequisites:
{chr(10).join([f'  - "{prereq}"' for prereq in prerequisites])}
teaching_scaffolds:
  before_you_learn: ""
  common_misunderstanding: ""
  real_world_analogy: ""
  key_takeaway: ""
---

## Intro

Welcome to Chapter {chapter_num} of the Physical AI & Humanoid Robotics textbook. In this chapter, we'll explore fundamental concepts that form the basis of modern robotics and artificial intelligence. This chapter builds on the previous concepts and prepares you for more advanced topics in subsequent chapters.

## Learning Objectives

By the end of this chapter, you will be able to:
- {chr(10) + '- '.join(learning_outcomes)}

These objectives are designed following Bloom's Taxonomy to ensure comprehensive understanding and application of concepts.

## Hook

Consider how robots in science fiction seamlessly interact with their environment. What makes this possible in real-world robotics? Understanding the foundational concepts in this chapter will illuminate the path from digital simulation to real-world deployment.

## Concept

This section introduces the core concepts and theoretical foundations of the topic. We'll explore the principles, mechanisms, and frameworks that underpin the subject matter. Detailed explanations will help you grasp both the "what" and the "why" behind the concepts.

## Mermaid Diagram

```mermaid
graph TD
    A[Physical AI Concept] --> B[Implementation]
    B --> C[Application]
    C --> D[Real-World Deployment]
    A -.-> D
```

This diagram illustrates the relationship between theoretical concepts and their practical implementation in robotics.

## Code Example

```python
# Example implementation demonstrating the concepts discussed
def example_robot_behavior():
    """
    Example function showing basic robot behavior implementation
    """
    print("Initializing robot behavior...")
    # Implementation details would go here
    return True

# Example usage
if __name__ == "__main__":
    success = example_robot_behavior()
    if success:
        print("Robot behavior initialized successfully")
    else:
        print("Failed to initialize robot behavior")
```

This code example demonstrates how the theoretical concepts translate into practical implementation using ROS 2 and Python.

## Exercises

1. **Conceptual Exercise**: Describe how the concepts in this chapter apply to a real-world robotics scenario.
2. **Implementation Exercise**: Modify the provided code example to implement a different behavior.
3. **Analysis Exercise**: Compare the approach described in this chapter with alternative methods.

Solutions to these exercises can be found in the instructor resources.

## Summary

In this chapter, we covered the fundamental concepts of [topic]. We explored the theoretical foundations, practical implementations, and real-world applications. Key takeaways include [key point 1], [key point 2], and [key point 3].

## Preview Next Chapter

In the next chapter, we'll build upon these concepts by exploring [next chapter topic]. This will deepen your understanding and prepare you for more advanced applications in robotics and AI.

---
Last updated: {datetime.now().strftime('%Y-%m-%d')}
Generated by Physical AI & Humanoid Robotics textbook generation system
"""
    return template


def generate_chapter(
    output_dir: Path,
    title: str,
    description: str,
    learning_outcomes: List[str],
    prerequisites: List[str],
    part_name: str,
    chapter_num: int,
    chapter_slug: str
) -> Path:
    """
    Generates a chapter file with the specified parameters.

    Args:
        output_dir: Directory where the chapter should be saved
        title: Chapter title
        description: Chapter description
        learning_outcomes: List of learning outcomes (3-5 items)
        prerequisites: List of prerequisites
        part_name: Name of the part (e.g., "part-1-foundations-lab")
        chapter_num: Chapter number
        chapter_slug: Chapter slug for filename

    Returns:
        Path to the created chapter file
    """
    # Create part directory if it doesn't exist
    part_dir = output_dir / part_name
    part_dir.mkdir(parents=True, exist_ok=True)

    # Create the file name
    filename = f"chapter-{chapter_num:02d}-{chapter_slug}.mdx"
    filepath = part_dir / filename

    # Create the chapter content
    content = create_chapter_template(
        title=title,
        description=description,
        learning_outcomes=learning_outcomes,
        prerequisites=prerequisites,
        part_name=part_name,
        chapter_num=chapter_num,
        chapter_slug=chapter_slug
    )

    # Write the content to the file
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    return filepath


def main():
    """Main function to run the chapter generation."""
    if len(sys.argv) < 2:
        print("Usage: python generate_chapters.py <output_directory> [config_file]")
        print("")
        print("If no config_file is provided, generates a sample chapter.")
        sys.exit(1)

    output_dir = Path(sys.argv[1])
    config_file = Path(sys.argv[2]) if len(sys.argv) > 2 else None

    # If no config file provided, create a sample chapter
    if not config_file or not config_file.exists():
        print("Generating sample chapter...")

        sample_path = generate_chapter(
            output_dir=output_dir,
            title="Sample Chapter: Introduction to Physical AI",
            description="This chapter introduces the fundamental concepts of Physical AI",
            learning_outcomes=[
                "Define Physical AI and embodied intelligence",
                "Explain the difference between digital and physical AI",
                "Identify key applications of Physical AI"
            ],
            prerequisites=[
                "Basic understanding of robotics concepts",
                "Python programming fundamentals"
            ],
            part_name="part-1-foundations-lab",
            chapter_num=1,
            chapter_slug="introduction-to-physical-ai"
        )

        print(f"Sample chapter created at: {sample_path}")
        return

    # If config file provided, parse it and generate chapters
    with open(config_file, 'r', encoding='utf-8') as f:
        config = yaml.safe_load(f)

    chapters_config = config.get('chapters', [])

    if not chapters_config:
        print("No chapters found in config file")
        sys.exit(1)

    for chapter_config in chapters_config:
        try:
            filepath = generate_chapter(
                output_dir=output_dir,
                title=chapter_config['title'],
                description=chapter_config['description'],
                learning_outcomes=chapter_config['learning_outcomes'],
                prerequisites=chapter_config.get('prerequisites', []),
                part_name=chapter_config['part_name'],
                chapter_num=chapter_config['chapter_num'],
                chapter_slug=chapter_config['chapter_slug']
            )
            print(f"Created chapter: {filepath}")
        except KeyError as e:
            print(f"Missing required field in chapter config: {e}")
            continue
        except Exception as e:
            print(f"Error creating chapter: {e}")
            continue


if __name__ == "__main__":
    main()